### ISSUE TITLE
GiftEvents don't load in 1.11.1

### ISSUE THREAD

**Issue by Ironic8b498** [omwah/GiftEvents#15]
Just updated to bungeecord 1216, Spigot 1.11.1 at server bootup I get this in my logs

`[18:20:32] [Server thread/INFO]: [GiftEvents] Enabling GiftEvents v2.4.2
[18:20:32] [Server thread/ERROR]: Cannot load plugins/GiftEvents/events.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 80, column 7:
          items:
          ^
expected <block end>, but found BlockSequenceStart
 in 'string', line 83, column 9:
            - { id: DIAMOND, enchantments: { ... 
            ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at com.github.omwah.giftevents.GiftEventsPlugin.loadEvents(GiftEventsPlugin.java:148) [GiftEvents_2.4.2.jar:?]
	at com.github.omwah.giftevents.GiftEventsPlugin.onEnable(GiftEventsPlugin.java:66) [GiftEvents_2.4.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 80, column 7:
          items:
          ^
expected <block end>, but found BlockSequenceStart
 in 'string', line 83, column 9:
            - { id: DIAMOND, enchantments: { ... 
            ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	... 16 more
[18:20:32] [Server thread/ERROR]: [GiftEvents] events section not found in configuration, could not enable events
`

**Comment by AlexMl** [comment]
Thank you for your report. I'm going to update GiftEvents soon.

**Comment by AlexMl** [comment]
I just tested with 1.11.1 and it seems to run fine. There seems to be an issue with your config files. Please provide them, so I can fix it.

**Comment by Ironic8b498** [comment]
[https://dl.dropboxusercontent.com/u/81218539/config.zip](url)

**Comment by Ironic8b498** [comment]
I removed the added line I added on the Christmas event and it loads fine now, it loaded on 1.11, did do it right on how to add a second item?

**Comment by AlexMl** [comment]
It should work, when you do it like that:
https://www.aubli.de/pictures/Screenshot_20161223-003119.png
